/**
 * Discord / Slack の設定定義。
 *
 * 接続設定 (enabled / token / guild 等) は DB (`discord_config` / `slack_config`) 優先で
 * env フォールバック。 token は secret として扱い、 実値を API に出さない。
 */

import type { SettingDefinition } from "../types.js";

export const DISCORD_SETTINGS: readonly SettingDefinition[] = [
  {
    key: "discord.enabled",
    section: "discord",
    label: "Discord bot を有効化",
    description: "OFF にすると bot を起動しない。",
    kind: "boolean",
    envName: "CONCORDIA_DISCORD_ENABLED",
    dbKey: "conn_enabled",
    defaultValue: false,
    editable: true,
  },
  {
    key: "discord.token",
    section: "discord",
    label: "Bot トークン",
    description: "Discord bot token。 DB へは暗号化して保存し、 API には実値を返さない。",
    kind: "secret",
    envName: "CONCORDIA_DISCORD_TOKEN",
    dbKey: "conn_token_enc",
    defaultValue: null,
    editable: true,
  },
  {
    key: "discord.guild_id",
    section: "discord",
    label: "Guild ID",
    description: "運用対象のサーバ (guild) ID。",
    kind: "string",
    envName: "CONCORDIA_DISCORD_GUILD_ID",
    dbKey: "conn_guild_id",
    defaultValue: null,
    editable: true,
  },
  {
    key: "discord.application_id",
    section: "discord",
    label: "Application ID",
    description: "スラッシュコマンド登録に使う application ID。",
    kind: "string",
    envName: "CONCORDIA_DISCORD_APPLICATION_ID",
    dbKey: "conn_application_id",
    defaultValue: null,
    editable: true,
  },
  {
    key: "discord.permission_requests_enabled",
    section: "discord",
    label: "権限確認を Discord へ流す",
    description: "セッションの permission 要求を Discord に投稿するか。 OFF だと通知が出ない。",
    kind: "boolean",
    envName: "CONCORDIA_DISCORD_PERMISSION_REQUESTS_ENABLED",
    dbKey: "conn_permission_requests_enabled",
    defaultValue: false,
    editable: true,
  },
  {
    key: "discord.message_optimization_enabled",
    section: "discord",
    label: "メッセージ最適化",
    description: "投稿の分割・圧縮を行うか。",
    kind: "boolean",
    envName: "CONCORDIA_DISCORD_MESSAGE_OPTIMIZATION_ENABLED",
    dbKey: "conn_message_optimization_enabled",
    defaultValue: true,
    editable: true,
  },
  {
    key: "discord.forum_mode",
    section: "discord",
    label: "フォーラムモード",
    description:
      "セッションをフォーラム投稿として扱うレイアウト移行フラグ。 誤操作を避けるため env 専用 (接続 UI から切り替えない)。",
    kind: "boolean",
    envName: "CONCORDIA_DISCORD_FORUM_MODE",
    dbKey: null,
    defaultValue: false,
    editable: false,
  },
  {
    key: "discord.embedded",
    section: "discord",
    label: "bot を同一プロセスで動かす",
    description: "OFF なら別 worker プロセスで動かす。 変更には再起動が要る。",
    kind: "boolean",
    envName: "CONCORDIA_DISCORD_EMBEDDED",
    dbKey: null,
    defaultValue: true,
    editable: false,
  },
  {
    key: "discord.subsidiary_autostart",
    section: "discord",
    label: "子会社 bot の自動起動",
    description: "出張先 (子会社) bot を boot 時に起動するか。",
    kind: "boolean",
    envName: "CONCORDIA_DISCORD_SUBSIDIARY_AUTOSTART",
    dbKey: null,
    defaultValue: false,
    editable: false,
  },
  {
    key: "discord.forum_webhook_name",
    section: "discord",
    label: "フォーラム webhook 名",
    description: "フォーラム投稿に使う webhook の表示名。",
    kind: "string",
    envName: "CONCORDIA_DISCORD_FORUM_WEBHOOK_NAME",
    dbKey: null,
    defaultValue: null,
    editable: false,
  },
  {
    key: "discord.forum_webhook_avatar_url",
    section: "discord",
    label: "フォーラム webhook アバター",
    description: "フォーラム投稿 webhook のアバター画像 URL。",
    kind: "string",
    envName: "CONCORDIA_DISCORD_FORUM_WEBHOOK_AVATAR_URL",
    dbKey: null,
    defaultValue: null,
    editable: false,
  },
  {
    key: "discord.webhook_send_timeout_ms",
    section: "discord",
    label: "webhook 送信タイムアウト (ms)",
    description: "webhook 送信を打ち切るまでの時間。",
    kind: "integer",
    envName: "CONCORDIA_DISCORD_WEBHOOK_SEND_TIMEOUT_MS",
    dbKey: null,
    defaultValue: null,
    editable: false,
  },
  {
    key: "discord.question_post_delay_ms",
    section: "discord",
    label: "質問投稿の遅延 (ms)",
    description: "お伺い投稿をまとめるための待ち時間。",
    kind: "integer",
    envName: "CONCORDIA_QUESTION_POST_DELAY_MS",
    dbKey: null,
    defaultValue: null,
    editable: false,
  },
] as const;

export const SLACK_SETTINGS: readonly SettingDefinition[] = [
  {
    key: "slack.enabled",
    section: "slack",
    label: "Slack bot を有効化",
    description: "OFF にすると bot を起動しない。",
    kind: "boolean",
    envName: "CONCORDIA_SLACK_ENABLED",
    dbKey: "enabled",
    defaultValue: false,
    editable: true,
  },
  {
    key: "slack.bot_token",
    section: "slack",
    label: "Bot トークン (xoxb-)",
    description: "Slack bot token。 DB へは暗号化して保存し、 API には実値を返さない。",
    kind: "secret",
    envName: "CONCORDIA_SLACK_BOT_TOKEN",
    dbKey: "bot_token_enc",
    defaultValue: null,
    editable: true,
  },
  {
    key: "slack.app_token",
    section: "slack",
    label: "App トークン (xapp-)",
    description: "Socket Mode 用の app token。 API には実値を返さない。",
    kind: "secret",
    envName: "CONCORDIA_SLACK_APP_TOKEN",
    dbKey: "app_token_enc",
    defaultValue: null,
    editable: true,
  },
  {
    key: "slack.channel_id",
    section: "slack",
    label: "Hub チャンネル ID",
    description: "セッション一覧 Canvas を置く hub チャンネル。",
    kind: "string",
    envName: "CONCORDIA_SLACK_CHANNEL_ID",
    dbKey: "channel_id",
    defaultValue: null,
    editable: true,
  },
  {
    key: "slack.archive_delay_min",
    section: "slack",
    label: "チャンネル archive までの分",
    description: "セッション終了後、 専用チャンネルを archive するまでの待ち時間。",
    kind: "integer",
    envName: "CONCORDIA_SLACK_ARCHIVE_DELAY_MIN",
    dbKey: null,
    defaultValue: 30,
    editable: false,
  },
  {
    key: "slack.working_idle_sec",
    section: "slack",
    label: "作業中表示の idle 判定 (秒)",
    description: "この秒数更新が無ければ 「作業中」 表示を落とす。 最小 15。",
    kind: "integer",
    envName: "CONCORDIA_SLACK_WORKING_IDLE_SEC",
    dbKey: null,
    defaultValue: 60,
    editable: false,
  },
  {
    key: "slack.cost_refresh_min",
    section: "slack",
    label: "コスト再計算の間隔 (分)",
    description: "Slack へ出すコスト表示の更新間隔。 最小 10。",
    kind: "integer",
    envName: "CONCORDIA_SLACK_COST_REFRESH_MIN",
    dbKey: null,
    defaultValue: 10,
    editable: false,
  },
] as const;
