/**
 * コア (本体起動) とワークスペースの設定定義。
 *
 * コア系は bind 先や DB パスなど **プロセス起動時にしか効かない**ものが中心なので
 * `editable: false` (表示のみ)。 「UI から変えられるように見えて再起動するまで効かない」
 * を作らないため、 編集経路は持たせない。
 */

import type { SettingDefinition } from "../types.js";

export const CORE_SETTINGS: readonly SettingDefinition[] = [
  {
    key: "core.host",
    section: "core",
    label: "bind ホスト",
    description: "HTTP API の待ち受けアドレス。 loopback 以外にすると信頼境界が変わる。 変更には再起動が要る。",
    kind: "string",
    envName: "CONCORDIA_HOST",
    dbKey: null,
    defaultValue: "127.0.0.1",
    editable: false,
  },
  {
    key: "core.port",
    section: "core",
    label: "bind ポート",
    description: "HTTP API の待ち受けポート。 正本は Excubitor catalog。 変更には再起動が要る。",
    kind: "integer",
    envName: "CONCORDIA_PORT",
    dbKey: null,
    defaultValue: 11111,
    editable: false,
  },
  {
    key: "core.db_path",
    section: "core",
    label: "DB パス",
    description: "SQLite の配置。 既定はサービス cwd 直下の concordia.db。 変更には再起動が要る。",
    kind: "string",
    envName: "CONCORDIA_DB_PATH",
    dbKey: null,
    defaultValue: null,
    editable: false,
  },
  {
    key: "core.secret_key",
    section: "core",
    label: "秘密鍵 (secret-box)",
    description: "DB に保存するトークンの暗号化鍵。 未設定だと token を暗号化保存できない。",
    kind: "secret",
    envName: "CONCORDIA_SECRET_KEY",
    dbKey: null,
    defaultValue: null,
    editable: false,
  },
  {
    key: "core.spawn_default_cwd",
    section: "core",
    label: "spawn 既定 cwd",
    description: "/v1/spawn で cwd 省略時に使う作業ディレクトリ。 未設定なら spawn は fail-closed で拒否する。",
    kind: "string",
    envName: "CONCORDIA_SPAWN_DEFAULT_CWD",
    dbKey: null,
    defaultValue: null,
    editable: false,
  },
  {
    key: "core.spawn_token_path",
    section: "core",
    label: "spawn token ファイル",
    description: "spawn token の置き場。 docker / systemd で volume 分離するとき上書きする。",
    kind: "string",
    envName: "CONCORDIA_SPAWN_TOKEN_PATH",
    dbKey: null,
    defaultValue: null,
    editable: false,
  },
  {
    key: "core.restart_dry_run",
    section: "core",
    label: "再起動 dry-run",
    description: "1 のとき POST /v1/admin/restart が実際の spawn / exit を行わない (テスト用)。",
    kind: "boolean",
    envName: "CONCORDIA_RESTART_DRY_RUN",
    dbKey: null,
    defaultValue: false,
    editable: false,
  },
] as const;

export const WORKSPACE_SETTINGS: readonly SettingDefinition[] = [
  {
    key: "workspace.roots",
    section: "workspace",
    label: "ワークスペースルート",
    description:
      "ローカルクローンを並べた親ディレクトリの一覧。 先頭がプライマリ。 Work ページの repo 走査と Memoria 解決の対象。",
    kind: "string-list",
    envName: "CONCORDIA_WORKSPACE_ROOTS",
    dbKey: "admin.workspace_roots",
    defaultValue: [],
    editable: true,
  },
  {
    key: "workspace.primary_root",
    section: "workspace",
    label: "プライマリルート (旧キー)",
    description:
      "単一ルート時代の後方互換キー。 ワークスペースルート一覧が空のときだけ参照される。 通常は一覧側を編集する。",
    kind: "string",
    envName: "CONCORDIA_WORKSPACE_ROOT",
    dbKey: "admin.workspace_root",
    defaultValue: null,
    editable: true,
  },
  {
    key: "workspace.ludiars_root",
    section: "workspace",
    label: "LUDIARS_ROOT (注入 env)",
    description:
      "Excubitor が spawn 時に注入するワークスペースルート。 ワークスペースルート未設定時の既定になる。 サービス側からは変更できない。",
    kind: "string",
    envName: "LUDIARS_ROOT",
    dbKey: null,
    defaultValue: null,
    editable: false,
  },
  {
    key: "workspace.github_org",
    section: "workspace",
    label: "GitHub Organization",
    description: "PR / repo 操作の owner 解決に使う Organization 名。",
    kind: "string",
    envName: "CONCORDIA_GITHUB_ORG",
    dbKey: "admin.github_org",
    defaultValue: null,
    editable: true,
  },
  {
    key: "workspace.commit_forbidden_roots",
    section: "workspace",
    label: "コミット禁止ルート",
    description: "委託先がコミットしてはいけないディレクトリ (`;` 区切り)。 共有 checkout の保護に使う。",
    kind: "string-list",
    envName: "CONCORDIA_COMMIT_FORBIDDEN_ROOTS",
    dbKey: null,
    defaultValue: [],
    editable: false,
  },
  {
    key: "workspace.castra_cwd",
    section: "workspace",
    label: "Castra cwd 明示指定",
    description: "ワークスペースルート自体を Session cwd として許すときの明示指定。 通常は未設定。",
    kind: "string",
    envName: "CONCORDIA_CASTRA_CWD",
    dbKey: null,
    defaultValue: null,
    editable: false,
  },
  {
    key: "workspace.attachment_enforce",
    section: "workspace",
    label: "添付パス許可の強制",
    description:
      "許可ルート外の添付を実際に遮断するか。 OFF にすると拒否理由を記録するだけで遮断しない (audit のみ)。",
    kind: "boolean",
    envName: "CONCORDIA_ATTACHMENT_ENFORCE",
    dbKey: null,
    defaultValue: true,
    editable: false,
  },
  {
    key: "workspace.attachment_roots",
    section: "workspace",
    label: "添付の追加許可ルート",
    description: "ワークスペースルートと temp に加えて添付を許可するディレクトリ (`;` 区切り)。",
    kind: "string-list",
    envName: "CONCORDIA_ATTACHMENT_ROOTS",
    dbKey: null,
    defaultValue: [],
    editable: false,
  },
  {
    key: "workspace.session_logs_dir",
    section: "workspace",
    label: "セッションログ置き場",
    description: "作業ログ (transcript) の読み出し元ディレクトリ。",
    kind: "string",
    envName: "CONCORDIA_SESSION_LOGS_DIR",
    dbKey: null,
    defaultValue: null,
    editable: false,
  },
] as const;
