/**
 * セッション管制・コンパクション・委託・ハーネス・LLM の設定定義。
 *
 * 大半は周期・閾値のチューニング用 env で、 DB 上書きを持たない (表示のみ)。
 * DB 上書きがあるもの (委託の同時実行数・watchdog 等) は `editable: true`。
 */

import type { SettingDefinition } from "../types.js";

/** env のみ・整数・表示専用の定型項目を作る (定義の反復を減らすためのローカル helper)。 */
function envInteger(
  key: string,
  section: SettingDefinition["section"],
  label: string,
  envName: string,
  defaultValue: number | null,
  description: string,
): SettingDefinition {
  return { key, section, label, description, kind: "integer", envName, dbKey: null, defaultValue, editable: false };
}

/** env のみ・真偽値・表示専用の定型項目。 */
function envBoolean(
  key: string,
  section: SettingDefinition["section"],
  label: string,
  envName: string,
  defaultValue: boolean,
  description: string,
): SettingDefinition {
  return { key, section, label, description, kind: "boolean", envName, dbKey: null, defaultValue, editable: false };
}

export const LLM_SETTINGS: readonly SettingDefinition[] = [
  {
    key: "llm.disable_claude",
    section: "llm",
    label: "Claude 呼び出しを緊急停止",
    description: "ON で report / 日報 / summary flags / library 解析の claude CLI 呼び出しを止める。 通常の ON/OFF は runtime 制御側で行う。",
    kind: "boolean",
    envName: "CONCORDIA_DISABLE_CLAUDE",
    dbKey: null,
    defaultValue: false,
    editable: false,
  },
  envInteger("llm.claude_timeout_ms", "llm", "claude CLI タイムアウト (ms)", "CONCORDIA_CLAUDE_TIMEOUT_MS", 120_000, "rule 用 claude CLI サブプロセスを打ち切るまでの時間。"),
  {
    key: "llm.chat_renderer",
    section: "llm",
    label: "チャット描画エンジン",
    description: "中央チャット描画の方式。 空なら cli (サブスク Haiku)。",
    kind: "enum",
    envName: "CONCORDIA_CHAT_RENDERER",
    dbKey: null,
    defaultValue: "cli",
    editable: false,
    enumValues: ["cli", "template"],
  },
  {
    key: "llm.chat_model",
    section: "llm",
    label: "チャット描画モデル",
    description: "中央チャット描画に使うモデル。 空なら haiku。",
    kind: "string",
    envName: "CONCORDIA_CHAT_MODEL",
    dbKey: null,
    defaultValue: "haiku",
    editable: false,
  },
  {
    key: "llm.chat_mode",
    section: "llm",
    label: "チャットモード",
    description: "チャット処理の動作モード指定。",
    kind: "string",
    envName: "CONCORDIA_CHAT_MODE",
    dbKey: null,
    defaultValue: null,
    editable: false,
  },
  {
    key: "llm.chat_process_role",
    section: "llm",
    label: "チャットプロセス役割",
    description: "本体 / worker のどちらがチャット処理を担うかの識別子。 worker 起動時に設定される。",
    kind: "string",
    envName: "CONCORDIA_CHAT_PROCESS_ROLE",
    dbKey: null,
    defaultValue: null,
    editable: false,
  },
  {
    key: "llm.reaction_model_haiku",
    section: "llm",
    label: "リアクション用 Haiku モデル",
    description: "リアクションワークフローの軽量判定に使うモデル名。",
    kind: "string",
    envName: "CONCORDIA_REACTION_MODEL_HAIKU",
    dbKey: null,
    defaultValue: null,
    editable: false,
  },
  {
    key: "llm.reaction_model_sonnet",
    section: "llm",
    label: "リアクション用 Sonnet モデル",
    description: "リアクションワークフローの本処理に使うモデル名。",
    kind: "string",
    envName: "CONCORDIA_REACTION_MODEL_SONNET",
    dbKey: null,
    defaultValue: null,
    editable: false,
  },
  envInteger("llm.context_window_tokens", "llm", "コンテキスト長の想定 (tokens)", "CONCORDIA_CONTEXT_WINDOW_TOKENS", null, "コンテキスト使用率の推定に使う想定ウィンドウ長。"),
] as const;

export const SESSION_SETTINGS: readonly SettingDefinition[] = [
  envInteger("session.lost_after_sec", "session", "lost 判定 (秒)", "CONCORDIA_LOST_AFTER_SEC", 1800, "heartbeat 途絶からこの秒数で lost にする。 短くしすぎると作業中のセッションが lost 化する。"),
  envInteger("session.abandoned_after_sec", "session", "abandoned 判定 (秒)", "CONCORDIA_ABANDONED_AFTER_SEC", 86_400, "lost からこの秒数で abandoned にする。"),
  envInteger("session.lost_purge_after_sec", "session", "lost purge 猶予 (秒)", "CONCORDIA_LOST_PURGE_AFTER_SEC", 1800, "lost を purge するまでの猶予。"),
  envInteger("session.purge_after_days", "session", "イベント保持 (日)", "CONCORDIA_PURGE_AFTER_DAYS", 90, "session_events を自動 purge するまでの日数。"),
  envInteger("session.sweeper_interval_ms", "session", "sweeper 周期 (ms)", "CONCORDIA_SWEEPER_INTERVAL_MS", 60_000, "lost / abandoned / purge 判定の走査間隔。"),
  envBoolean("session.reaper_enabled", "session", "孤児プロセス回収", "CONCORDIA_REAPER_ENABLED", true, "終了済みセッションの残プロセスを回収する。"),
  envInteger("session.reaper_interval_ms", "session", "回収の走査間隔 (ms)", "CONCORDIA_REAPER_INTERVAL_MS", 300_000, "reaper の走査周期。"),
  envInteger("session.reaper_min_age_sec", "session", "回収の最小 age (秒)", "CONCORDIA_REAPER_MIN_AGE_SEC", 180, "起動からこの秒数未満のプロセスは回収対象にしない (登録レース回避)。"),
  envInteger("session.reaper_lost_grace_sec", "session", "回収の復帰猶予 (秒)", "CONCORDIA_REAPER_LOST_GRACE_SEC", 300, "lost 化から Lictor tree を回収するまでの復帰待ち。"),
  {
    key: "session.reaper_session_end_grace_sec",
    section: "session",
    label: "session-end 回収猶予 (秒)",
    description: "session-end 完了通知を待ってから、ended session の残プロセスを保険回収するまでの猶予。保存後の次回走査から反映する。",
    kind: "integer",
    envName: "CONCORDIA_REAPER_SESSION_END_GRACE_SEC",
    dbKey: "admin.reaper_session_end_grace_sec",
    defaultValue: 300,
    editable: true,
    minValue: 1,
  },
  envBoolean("session.stall_nudge_enabled", "session", "停止セッションの続行 nudge", "CONCORDIA_STALL_NUDGE_ENABLED", true, "停止したセッションに続行を促す。"),
  envInteger("session.stall_nudge_interval_ms", "session", "停止 nudge の走査間隔 (ms)", "CONCORDIA_STALL_NUDGE_INTERVAL_MS", 600_000, "停止判定の走査周期。"),
  envInteger("session.stall_idle_sec", "session", "停止とみなす無更新 (秒)", "CONCORDIA_STALL_IDLE_SEC", 600, "transcript がこの秒数更新されなければ停止とみなす。 既定は巡回間隔と同じ 10 分 (2026-08-09 neco 指示)。"),
  envInteger("session.stall_nudge_cooldown_sec", "session", "停止 nudge の cooldown (秒)", "CONCORDIA_STALL_NUDGE_COOLDOWN_SEC", 600, "一度 nudge したら次まで空ける秒数。 既定は停止判定と同じ。"),
  envInteger("session.idle_nudge_sec", "session", "完了後の催促 (秒)", "CONCORDIA_IDLE_NUDGE_SEC", 120, "final_answer から依頼元へ通知するまでの秒数。 0 以下で無効。"),
  envInteger("session.inquiry_cache_sec", "session", "お伺いの再送抑止 (秒)", "CONCORDIA_INQUIRY_CACHE_SEC", 60, "同一 session / category のお伺いを抑える秒数。"),
  {
    key: "session.inquiry_score_min",
    section: "session",
    label: "判断カード採用の最低 score",
    description: "Genius 判断カードを採用する最低スコア (0..1)。 範囲外は既定に戻す。",
    kind: "string",
    envName: "CONCORDIA_INQUIRY_SCORE_MIN",
    dbKey: null,
    defaultValue: "0.6",
    editable: false,
  },
  {
    key: "session.default_supervisor",
    section: "session",
    label: "既定の上長",
    description: "`discord:<uid>` 形式。 空なら上長メンションを行わない。",
    kind: "string",
    envName: "CONCORDIA_DEFAULT_SUPERVISOR",
    dbKey: null,
    defaultValue: null,
    editable: false,
  },
  {
    key: "session.satelles_launcher",
    section: "session",
    label: "Satelles 起動コマンド",
    description: "codex-sdk headless runner の起動コマンド (`;` 区切り)。 既定は PATH 上の satelles。",
    kind: "string-list",
    envName: "CONCORDIA_SATELLES_LAUNCHER",
    dbKey: null,
    defaultValue: ["satelles"],
    editable: false,
  },
] as const;

export const COMPACTION_SETTINGS: readonly SettingDefinition[] = [
  envBoolean("compaction.auto_enabled", "compaction", "自動コンパクション", "CONCORDIA_AUTO_COMPACTION", false, "コンテキスト使用率に応じて自動で圧縮を促す。"),
  envInteger("compaction.auto_pct", "compaction", "自動発火のしきい値 (%)", "CONCORDIA_COMPACTION_AUTO_PCT", null, "この使用率を超えたら自動コンパクションを発火する。"),
  envInteger("compaction.soft_pct", "compaction", "警告のしきい値 (%)", "CONCORDIA_COMPACTION_SOFT_PCT", null, "この使用率で警告を出す (発火はしない)。"),
  envInteger("compaction.cooldown_sec", "compaction", "cooldown (秒)", "CONCORDIA_COMPACTION_COOLDOWN_SEC", null, "一度コンパクションしたら次まで空ける秒数。"),
  envInteger("compaction.quiet_sec", "compaction", "静穏待ち (秒)", "CONCORDIA_COMPACTION_QUIET_SEC", null, "セッションが静かになってから発火するまでの待ち。"),
  envInteger("compaction.clear_wait_ms", "compaction", "clear 後の待ち (ms)", "CONCORDIA_COMPACTION_CLEAR_WAIT_MS", null, "コンテキスト clear 後に次の入力を送るまでの待ち。"),
  envInteger("compaction.timeout_ms", "compaction", "タイムアウト (ms)", "CONCORDIA_COMPACTION_TIMEOUT_MS", null, "コンパクション全体を打ち切るまでの時間。"),
  envInteger("compaction.elicit_timeout_ms", "compaction", "引き出しタイムアウト (ms)", "CONCORDIA_COMPACTION_ELICIT_TIMEOUT_MS", null, "引き継ぎ内容の生成を打ち切るまでの時間。"),
  envInteger("compaction.elicit_quiet_ms", "compaction", "引き出しの静穏待ち (ms)", "CONCORDIA_COMPACTION_ELICIT_QUIET_MS", null, "出力が止まってから完了とみなすまでの待ち。"),
  envInteger("compaction.elicit_poll_ms", "compaction", "引き出しのポーリング間隔 (ms)", "CONCORDIA_COMPACTION_ELICIT_POLL_MS", null, "引き継ぎ生成の進捗確認間隔。"),
  {
    key: "compaction.model",
    section: "compaction",
    label: "コンパクション用モデル",
    description: "引き継ぎ生成に使うモデル名。",
    kind: "string",
    envName: "CONCORDIA_COMPACTION_MODEL",
    dbKey: null,
    defaultValue: null,
    editable: false,
  },
] as const;

export const DELEGATION_SETTINGS: readonly SettingDefinition[] = [
  {
    key: "delegation.max_concurrency",
    section: "delegation",
    label: "委託の同時実行上限",
    description: "同時に走らせる委託 run の上限。",
    kind: "integer",
    envName: null,
    dbKey: "admin.delegation_max_concurrency",
    defaultValue: 4,
    editable: true,
    minValue: 0,
  },
  {
    key: "delegation.watchdog_enabled",
    section: "delegation",
    label: "委託 watchdog",
    description: "委託先が黙り込んだときに状況報告を促す。",
    kind: "boolean",
    envName: null,
    dbKey: "admin.delegation_watchdog_enabled",
    defaultValue: true,
    editable: true,
  },
  {
    key: "delegation.watchdog_idle_sec",
    section: "delegation",
    label: "watchdog の無応答判定 (秒)",
    description: "この秒数報告が無ければ nudge する。",
    kind: "integer",
    envName: null,
    dbKey: "admin.delegation_watchdog_idle_sec",
    defaultValue: 1800,
    editable: true,
    minValue: 1,
  },
  {
    key: "delegation.watchdog_max_nudges",
    section: "delegation",
    label: "watchdog の最大 nudge 回数",
    description: "同じ run に対して促す上限回数。",
    kind: "integer",
    envName: null,
    dbKey: "admin.delegation_watchdog_max_nudges",
    defaultValue: 3,
    editable: true,
    minValue: 1,
  },
  envInteger("delegation.watchdog_interval_ms", "delegation", "watchdog の走査間隔 (ms)", "CONCORDIA_DELEGATION_WATCHDOG_INTERVAL_MS", null, "watchdog の走査周期。"),
  envBoolean("delegation.fast_mode", "delegation", "fast mode", "CONCORDIA_DELEGATION_FAST_MODE", false, "委託先セッションを fast mode で起動する。"),
  envBoolean("delegation.goal_and_go", "delegation", "goal-and-go", "CONCORDIA_DELEGATION_GOAL_AND_GO", false, "委託先の自走継続を既定で有効にする。"),
  envInteger("delegation.goal_and_go_idle_sec", "delegation", "自走の再開待ち (秒)", "CONCORDIA_GOAL_AND_GO_IDLE_SEC", 300, "完了後この秒数で自走を再開する。"),
  envInteger("delegation.goal_and_go_max_continuations", "delegation", "自走の最大継続回数", "CONCORDIA_GOAL_AND_GO_MAX_CONTINUATIONS", 6, "人間のターンが挟まるまでの自走上限。"),
  envInteger("delegation.goal_and_go_max_runtime_sec", "delegation", "自走の最大実行時間 (秒)", "CONCORDIA_GOAL_AND_GO_MAX_RUNTIME_SEC", 7200, "人間の関与なしに走り続けられる上限。"),
  envInteger("delegation.subsidiary_guard_timeout_ms", "delegation", "子会社ガードのタイムアウト (ms)", "CONCORDIA_SUBSIDIARY_GUARD_TIMEOUT_MS", null, "子会社 delegation のガード判定を打ち切るまでの時間。"),
] as const;

export const HARNESS_SETTINGS: readonly SettingDefinition[] = [
  {
    key: "harness.main_push_allowlist",
    section: "harness",
    label: "main 直 push 許可リスト",
    description: "main への直接 push を許可するリポジトリ名または絶対パスの一覧。 空配列は例外なしを明示する。",
    kind: "string-list",
    envName: "HARNESS_MAIN_PUSH_ALLOWLIST",
    dbKey: "harness.main_push_allowlist",
    defaultValue: ["KuzuSurvivors", "MakaiNui"],
    editable: true,
    listEnvFormat: "comma-or-newline",
  },
  {
    key: "harness.strong_impl_models",
    section: "harness",
    label: "強推論の実装モデル",
    description: "実装ゲートで 「強い」 と扱うモデル名の一覧。",
    kind: "string-list",
    envName: null,
    dbKey: "harness.strong_impl_models",
    defaultValue: ["fable", "sol-ultra"],
    editable: true,
  },
  {
    key: "harness.intent_model",
    section: "harness",
    label: "意図解析モデル",
    description: "プロンプト意図の判定に使うモデル名。",
    kind: "string",
    envName: "CONCORDIA_HARNESS_INTENT_MODEL",
    dbKey: null,
    defaultValue: null,
    editable: false,
  },
  envBoolean("harness.prompt_analyzer", "harness", "プロンプト解析", "CONCORDIA_PROMPT_ANALYZER", false, "ローカル LLM によるプロンプト解析を有効にする。"),
  {
    key: "harness.prompt_analyzer_base_url",
    section: "harness",
    label: "解析 LLM の base URL",
    description: "OpenAI 互換エンドポイント。 既定はローカル Ollama。",
    kind: "string",
    envName: "CONCORDIA_PROMPT_ANALYZER_BASE_URL",
    dbKey: null,
    defaultValue: "http://127.0.0.1:11434/v1",
    editable: false,
  },
  {
    key: "harness.prompt_analyzer_model",
    section: "harness",
    label: "解析 LLM のモデル",
    description: "プロンプト解析に使うモデル名。",
    kind: "string",
    envName: "CONCORDIA_PROMPT_ANALYZER_MODEL",
    dbKey: null,
    defaultValue: null,
    editable: false,
  },
  {
    key: "harness.prompt_analyzer_api_key",
    section: "harness",
    label: "解析 LLM の API キー",
    description: "ローカル LLM では通常不要。 API には実値を返さない。",
    kind: "secret",
    envName: "CONCORDIA_PROMPT_ANALYZER_API_KEY",
    dbKey: null,
    defaultValue: null,
    editable: false,
  },
  envInteger("harness.prompt_analyzer_timeout_ms", "harness", "解析タイムアウト (ms)", "CONCORDIA_PROMPT_ANALYZER_TIMEOUT_MS", null, "プロンプト解析を打ち切るまでの時間。"),
  envInteger("harness.prompt_analyzer_max_tokens", "harness", "解析の最大トークン", "CONCORDIA_PROMPT_ANALYZER_MAX_TOKENS", null, "解析応答の上限トークン。"),
  envBoolean("harness.prompt_research", "harness", "事前調査", "CONCORDIA_PROMPT_RESEARCH", false, "Anatomia / Thaleia を引いてプロンプトに事前調査を添える。"),
  {
    key: "harness.prompt_research_anatomia_url",
    section: "harness",
    label: "事前調査の Anatomia URL",
    description: "事前調査だけ別の Anatomia を向けるときの上書き。 未設定なら共通設定に従う。",
    kind: "string",
    envName: "CONCORDIA_PROMPT_RESEARCH_ANATOMIA_URL",
    dbKey: null,
    defaultValue: null,
    editable: false,
  },
  {
    key: "harness.prompt_research_thaleia_url",
    section: "harness",
    label: "事前調査の Thaleia URL",
    description: "事前調査だけ別の Thaleia を向けるときの上書き。 未設定なら共通設定に従う。",
    kind: "string",
    envName: "CONCORDIA_PROMPT_RESEARCH_THALEIA_URL",
    dbKey: null,
    defaultValue: null,
    editable: false,
  },
] as const;
